version: '2'
services:
  elastic-app:
    image: elastic
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://elastic-mysql:3306/elastic?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://elastic-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://elastic-elasticsearch:9200
    ports:
      - 8885:8885
  elastic-mysql:
    extends:
      file: mysql.yml
      service: elastic-mysql
  elastic-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elastic-elasticsearch
